// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TCIS.TTOS.ToolHelper.DAL;

#nullable disable

namespace TCIS.TTOS.ToolHelper.Dal.Migrations
{
    [DbContext(typeof(ToolHelperDbContext))]
    [Migration("20260311040102_AddRedisInstances")]
    partial class AddRedisInstances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.DeploymentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Version")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_deployment_histories_status");

                    b.HasIndex("ServiceId", "StartedAt")
                        .HasDatabaseName("ix_deployment_histories_service_started");

                    b.ToTable("deployment_histories", (string)null);
                });

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.MonitoredHost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgentPort")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Os")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SshPassword")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("SshPort")
                        .HasColumnType("integer");

                    b.Property<string>("SshPrivateKeyPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SshUsername")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_monitored_hosts_ip");

                    b.HasIndex("IsActive", "Status")
                        .HasDatabaseName("ix_monitored_hosts_active_status");

                    b.ToTable("monitored_hosts", (string)null);
                });

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.MonitoredService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComposeFilePath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ContainerName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeployCommand")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DockerfilePath")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("HealthCheckUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastDeployedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastDeploymentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("RestartCommand")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StopCommand")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("WorkingDirectory")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_monitored_services_name");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_monitored_services_type");

                    b.HasIndex("HostId", "IsActive")
                        .HasDatabaseName("ix_monitored_services_host_active");

                    b.HasIndex("HostId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_monitored_services_host_name");

                    b.ToTable("monitored_services", (string)null);
                });

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.NotificationOutbox", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Pref")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpxTn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpxTn", "CreatedAt")
                        .HasDatabaseName("ix_outbox_spx");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasDatabaseName("ix_outbox_pending");

                    b.HasIndex("EventKey", "UserId", "Channel")
                        .IsUnique();

                    b.ToTable("notification_outbox", (string)null);
                });

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.RedisInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Database")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Password")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HostId", "IsActive")
                        .HasDatabaseName("ix_redis_instances_host_active");

                    b.HasIndex("HostId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_redis_instances_host_name");

                    b.ToTable("redis_instances", (string)null);
                });

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.ShipmentPollLock", b =>
                {
                    b.Property<string>("SpxTn")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LockedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SpxTn");

                    b.HasIndex("LockedUntil")
                        .HasDatabaseName("ix_poll_locks_until");

                    b.ToTable("shipment_poll_locks", (string)null);
                });

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.TrackingEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BuyerMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentLocation")
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MilestoneCode")
                        .HasColumnType("integer");

                    b.Property<string>("MilestoneName")
                        .HasColumnType("text");

                    b.Property<string>("NextLocation")
                        .HasColumnType("jsonb");

                    b.Property<string>("RawRecord")
                        .HasColumnType("jsonb");

                    b.Property<string>("SellerMessage")
                        .HasColumnType("text");

                    b.Property<string>("SpxTn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("SpxTn", "EventTime")
                        .HasDatabaseName("ix_tracking_events_tn_time");

                    b.HasIndex("SpxTn", "EventTime", "TrackingCode")
                        .IsUnique();

                    b.ToTable("tracking_events", (string)null);
                });

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.TrackingShipment", b =>
                {
                    b.Property<string>("SpxTn")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ClientOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentFullAddress")
                        .HasColumnType("text");

                    b.Property<double?>("CurrentLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("CurrentLng")
                        .HasColumnType("double precision");

                    b.Property<string>("CurrentLocationName")
                        .HasColumnType("text");

                    b.Property<int?>("DeliverType")
                        .HasColumnType("integer");

                    b.Property<string>("Fingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.Property<string>("LastEventCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("LastEventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastMessage")
                        .HasColumnType("text");

                    b.Property<string>("LastMilestoneName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastPolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastRawJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("NextFullAddress")
                        .HasColumnType("text");

                    b.Property<double?>("NextLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("NextLng")
                        .HasColumnType("double precision");

                    b.Property<string>("NextLocationName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("NextPollAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PollFailCount")
                        .HasColumnType("integer");

                    b.Property<int>("PollIntervalSec")
                        .HasColumnType("integer");

                    b.Property<int>("RawVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SpxTn");

                    b.HasIndex("ClientOrderId")
                        .HasDatabaseName("ix_tracking_shipments_client_order_id");

                    b.HasIndex("IsTerminal", "NextPollAt")
                        .HasDatabaseName("ix_tracking_shipments_due_poll");

                    b.ToTable("tracking_shipments", (string)null);
                });

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.TrackingSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Pref")
                        .HasColumnType("integer");

                    b.Property<string>("SpxTn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpxTn", "IsActive")
                        .HasDatabaseName("ix_tracking_subscriptions_active");

                    b.HasIndex("UserId", "SpxTn")
                        .IsUnique();

                    b.ToTable("tracking_subscriptions", (string)null);
                });

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.DeploymentHistory", b =>
                {
                    b.HasOne("TCIS.TTOS.ToolHelper.Dal.Entities.MonitoredService", "Service")
                        .WithMany("DeploymentHistories")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.MonitoredService", b =>
                {
                    b.HasOne("TCIS.TTOS.ToolHelper.Dal.Entities.MonitoredHost", "Host")
                        .WithMany("Services")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.NotificationOutbox", b =>
                {
                    b.HasOne("TCIS.TTOS.ToolHelper.Dal.Entities.TrackingShipment", "Shipment")
                        .WithMany("OutboxMessages")
                        .HasForeignKey("SpxTn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.RedisInstance", b =>
                {
                    b.HasOne("TCIS.TTOS.ToolHelper.Dal.Entities.MonitoredHost", "MonitoredHost")
                        .WithMany("RedisInstances")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredHost");
                });

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.ShipmentPollLock", b =>
                {
                    b.HasOne("TCIS.TTOS.ToolHelper.Dal.Entities.TrackingShipment", "Shipment")
                        .WithOne("PollLock")
                        .HasForeignKey("TCIS.TTOS.ToolHelper.Dal.Entities.ShipmentPollLock", "SpxTn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.TrackingEvent", b =>
                {
                    b.HasOne("TCIS.TTOS.ToolHelper.Dal.Entities.TrackingShipment", "Shipment")
                        .WithMany("Events")
                        .HasForeignKey("SpxTn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.TrackingSubscription", b =>
                {
                    b.HasOne("TCIS.TTOS.ToolHelper.Dal.Entities.TrackingShipment", "Shipment")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SpxTn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.MonitoredHost", b =>
                {
                    b.Navigation("RedisInstances");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.MonitoredService", b =>
                {
                    b.Navigation("DeploymentHistories");
                });

            modelBuilder.Entity("TCIS.TTOS.ToolHelper.Dal.Entities.TrackingShipment", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("OutboxMessages");

                    b.Navigation("PollLock");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
